import React, { Children, ReactNode } from 'react'
import AuthGuard from '@/components/AuthGuard'
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "MeetVerse",
  description: "Generated by create next app",
  icons: {
    icon: '/icons/logo.svg'
  }
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <AuthGuard>
      <div>
        <main>
          {children}
        </main>
      </div>
    </AuthGuard>
  )
}

export default RootLayout

